sudo: false
language: ruby
rvm:
  - ruby-head
  - ruby-2.5.0
  - jruby-9.1.7.0

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - bundle install

script:
  - bundle exec rake
