sudo: false
language: ruby
rvm:
  - ruby-head
  - ruby-2.5.0
  - jruby-9.1.7.0

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - apt-get update
  - apt-get install -y unzip
  - gem update --system
  - bundle install
  - wget https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip
  - unzip -p gnatsd-v0.9.4-linux-amd64.zip gnatsd-v0.9.4-linux-amd64/gnatsd > gnatsd
  - chmod +x gnatsd

before_script:
  - nohup ./gnatsd --addr 127.0.0.1 --port 4222 &

script:
  - bundle exec rake
